version: "2"

linters:
  enable:
    - bodyclose
    - gocritic
    - ineffassign
    - revive
    - staticcheck
    - unconvert
    - unparam

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
  revive:
    rules:
      - name: exported
        severity: warning

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  go: "1.25"
